### ISSUE TITLE
A paper question

### ISSUE THREAD

**Issue by qilong-zhang** [val-iisc/BPFC#1]
Hi，I'm a little confused about Fig. 1 in your paper. Could tell me how to generate subfigure (b), (c), (e), (d)?
Thanks!

**Comment by GaurangSriramanan** [comment]
Thank you for your interest in our work and apologies for the delayed response. 

An 8-bit image for example, can be considered as the sum of eight bit planes, each weighted by its relative importance, as shown in the figure below:

![quant](https://user-images.githubusercontent.com/66883477/84599614-f197c300-ae90-11ea-940c-7a23dbde8e3a.png)

Thus we generate Fig-1(b) in our [paper](https://arxiv.org/abs/2004.00306) by setting the five least significant bits (which corresponds to bit planes 4, 3, 2, 1 and 0) to zero for each pixel in the original 8-bit image.  Similarly, we generate Fig-1(c) and (d) by setting the six least significant bits, and seven least significant bits respectively to zero for each pixel. On the other hand, we generate Fig-1(e) by setting the three most significant bits (which corresponds to bit planes 7, 6 and 5) to zero for each pixel.
