### ISSUE TITLE
white-box attack Preliminaries

### ISSUE THREAD

**Issue by yearep7** [val-iisc/BPFC#4]
Can you tell me the specific disturbance and step size of FGSM and IFGSM in Table 1? Thank you

**Comment by SravantiAddepalli** [comment]
Thank you for your interest in our work. 

The overall perturbation is constrained to eps = 8/255 for both attacks. Details on step size and the number of steps can be found in the code:

FGSM: https://github.com/val-iisc/BPFC/blob/master/CIFAR10/bpfc_cifar10.py#:~:text=adv%20%3D%20FGSM_Attack_step(model%2Closs%2Cdata%2Ctarget%2Ceps%3Deps%2Csteps%3D1

IFGSM: https://github.com/val-iisc/BPFC/blob/master/CIFAR10/bpfc_cifar10.py#:~:text=adv%20%3D%20FGSM_Attack_step(model%2Closs%2Cdata%2Ctarget%2Ceps%3Deps%2Csteps%3D7

Hope this clarifies!
